
spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8 #最小空闲链接
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: nxy
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    auto: true
  condition:
    sechedule: false
hello:  good
nxy:
  age: 17
  name: ${random.value()}
logging:
  file: F:\\logs\quickweb\app.log
  level: debug
app:
  version: test-1.0
